name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      # Build in Node 20 (outside of the SWA action)
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci || npm i

      - name: Build (Angular prod)
        run: npm run build

      # Upload the built files; DO NOT let SWA action build again
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_WAVE_0A03DFF1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # Point directly to the built artifact and skip app build
          app_location: "dist/expense-tracker"
          output_location: ""              # must be empty when skip_app_build is true
          skip_app_build: true
          api_location: ""                 # no API

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_WAVE_0A03DFF1E }}
          action: "close"
